name: Dependabot auto-merge
# automerge_dependabot
on: pull_request

permissions:
  contents: write
  pull-requests: write

jobs:
  dependabot:
    runs-on: ubuntu-latest
    if: ${{ github.actor == 'dependabot[bot]' }}
    steps:
      - name: Dependabot metadata
        id: metadata
        uses: dependabot/fetch-metadata@v1
        with:
          github-token: "${{ secrets.WORKFLOW_SECRET }}"
      - name: Enable auto-merge for Dependabot PRs
          #if (contains(steps.metadata.outputs.dependency-names, 'actions/stale') || 
          #contains(steps.metadata.outputs.dependency-names, '@zeit/ncc') || 
          #contains(steps.metadata.outputs.dependency-names, 'ts-jest') || 
          #contains(steps.metadata.outputs.dependency-names, 'uuid') || 
          #contains(steps.metadata.outputs.dependency-names, 'jest-circus') || 
          #(contains(steps.metadata.outputs.dependency-names, 'actions/github-script') && 
          #steps.metadata.outputs.update-type == 'version-update:semver-major'))
        run: gh pr merge --auto --merge "$PR_URL"
        env:
          PR_URL: ${{github.event.pull_request.html_url}}
          GITHUB_TOKEN: ${{secrets.WORKFLOW_SECRET}}
  
  ChangeLog_Enforcer:
    runs-on: ubuntu-latest
    needs: [dependabot]
    permissions:
      contents: write
    steps:
      - name: Python Action
        uses: jge162/Action-workflows@1.0.1

      - name: Get pull request number
        id: get_pull_request_number
        run: echo "::set-output name=pull_request_number::${{ github.event.number }}"

      - name: Update DEPENDABOTLOG
        uses: stefanzweifel/changelog-updater-action@v1
        with:
          path-to-changelog: DEPENDABOTLOG.md
          latest-version: ${{ github.ref }}
          release-notes: |
            Pull request number for DEPENDABOTLOG is: [#${{ steps.get_pull_request_number.outputs.pull_request_number }}](${{ github.event.pull_request.html_url }})
      - name: Commit updated DEPENDABOTLOG
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          branch: main
          commit_message: Update DEPENDABOTLOG
          file_pattern: DEPENDABOTLOG.md
