name: Daily Commit

on:
  schedule:
    - cron: '0 17 * * *'
  workflow_dispatch:

jobs:
  daily-commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
          
      - name: Create commit message
        run: |
          echo -e "\nAll GitHub Actions are running fine. Check the [GitHub status page](https://www.githubstatus.com/) for more information." > commit_message.txt
        
      - name: Append message to commit log
        run: |
          echo -e "$(date): $(cat commit_message.txt)\n" >> COMMITLOG.md
          git config --global user.email "${{ secrets.EMAIL }}"
          git config --global user.name "<Jeremy Escobar>"
          git add COMMITLOG.md
          git commit -m "Automated commit: $(cat commit_message.txt)"
          git push
