name: My GitHub Action

on:
  workflow_dispatch:

  push:
    branches:
      - main
    paths:
      - "common/**"
      - "myservice/**"
    tags:
      - "*"
    if: |
      (startsWith(github.ref, 'refs/tags/')) || 
      (!startsWith(github.ref, 'refs/tags/') && 
      contains(github.event.head_commit.modified, 'common/') || 
      contains(github.event.head_commit.modified, 'myservice/'))

jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Run my command
        run: |
          # Add your command here
